FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y python3 python3-zmq python3-dev git

RUN git clone https://github.com/elastisim/elastisim-python.git

ENV PYTHONPATH "${PYTHONPATH}:/elastisim-python"
ENTRYPOINT ["python3", "/algorithm/algorithm.py"]